// Generated by CoffeeScript 1.9.1
var gutter = 20;
var base = 60;
var isMobile = false;

var selectedElem, originalPos;
(function() {
    function openTab(url) {
      var win = window.open(url, '_blank');
      win.focus();
    }
  
    $(function() {
      // ON CLICK
      $(document).on("click touchend", ".gridly .brick", function(event) {
        var $this, size, originalSize;
        event.preventDefault();
        event.stopPropagation();
        $this = $(this);
        
        // Open links
        var link = $this.attr('link');
        if (link != undefined) {
          openTab(link);
          return;
        }
        
        openOrCloseApp($this);
//        $('.gridly').gridly('draggable', 'off');
      });
      
      $(document).on("click touchend", ".back", function(event) {
        console.log('back');
        event.preventDefault();
        event.stopPropagation();
        openOrCloseApp(selectedElem);
        $('.gridly').gridly('layout');
      });
      
      function openOrCloseApp(elem) {
        toggleAppClasses(elem);
        if (selectedElem != undefined) {
          selectedElem.data('position', originalPos);
          if (selectedElem.is(elem)) {
            selectedElem = undefined;
            $('.desc-full').html('');
            return;
          }
        }
        
        selectedElem = elem;
        originalPos = selectedElem.data('position');
        elem.data('position', isMobile ? 0 : -1);
        $('.gridly').gridly('layout');
        $('.desc-full').html(elem.find('.desc').html());
      }
      
      function toggleAppClasses(elem) {
        $('.brick').toggleClass('hidden');
        $('.phone').toggleClass('enabled');
        $('body').toggleClass('enabled');
        elem.removeClass('hidden');
        elem.find('.title').toggleClass('hidden');
      }

      // DELETE
      $(document).on("click", ".gridly .delete", function(event) {
        var $this;
        event.preventDefault();
        event.stopPropagation();
        $this = $(this);
        $this.closest('.brick').remove();
        return $('.gridly').gridly('layout');
      });
    });

}).call(this);

(function($, viewport) {

    // Execute only after document has fully loaded
    $(document).ready(function() {
      return resizeGrid($, viewport);
    });

    // Execute code each time window size changes
    $(window).resize(
      viewport.changed(function(){
        return resizeGrid($, viewport);
      })
    );

    resizeGrid = function($, viewport) {
//        console.log(viewport.current());
        var b, g, c;
        
        if (viewport.is('xs')) {
          isMobile = true;
            b = 25;
            g = 18;
            c = 8;

        } else if (viewport.is('>=sm')) {
          isMobile = false;
            b = 60;
            g = 20;
            c = 10;
        }
        
        gutter = g;
        base = b;
        return $('.gridly').gridly({
              base: b,
              gutter: g,
              columns: c
        });
    }

})(jQuery, ResponsiveBootstrapToolkit);

function updateClock() {
    var today=new Date();
    var h = today.getHours();
    var m = today.getMinutes();
    if (h > 12) { h -= 12 };
    if (m < 10) { m = "0" + m };
    document.getElementById('clock').innerHTML = h+":"+m;
    var t = setTimeout(function(){updateClock()}, 1000);
}

updateClock();
